Coletor MPCE: atualizado para o novo layout
dadosjusbr/coletor-mpce pull request #1
Opened 2021-11-29 11:40 UTC by marcos-inja

## MPCE utilizando o novo layout
> Esse **PR** atualiza o coletor **MPCE**

2021-11-29 14:28 UTC, danielfireman requested changes

2021-11-29 14:28 UTC, danielfireman commented on Dockerfile
> +FROM python:3.8
Seria massa se a gente, ao menos, usasse a mesma imagem

Olha esse Dockerfile do MPAL https://github.com/dadosjusbr/coletor-mpal/blob/5307bff74bc5c32b402aca70bd0eca694803f595/Dockerfile

2021-11-29 14:28 UTC, danielfireman commented on src/data.py
> +                f"/output/{self.year}_{self.month}_remu.html"
seguir padrão de nomenclatura dos demais coletores (sei que não são os mesmos formatos)

2021-11-29 14:28 UTC, danielfireman commented on src/headers_keys.py
> +
Muitas linhas em branco no final?

2021-11-29 14:28 UTC, danielfireman commented on src/data.py
> +                f"/output/{self.year}_{self.month}_vi.xlsx"
Tem certeza que é xlsx? Pelo que vi é tudo html, não?

2021-11-29 14:28 UTC, danielfireman commented on src/metadado.py
> +    metadado.acesso = Coleta.Metadados.FormaDeAcesso.RASPAGEM_DIFICULTADA
Poderia adicionar um comentário aqui especificando o motivo dessa raspagem dificultada?

2021-11-29 14:28 UTC, danielfireman commented on src/output_test/expected_2018.json
> +                        "tipoReceita": "O"
Não é para ter tipo receita quando é despesa.

2021-11-29 14:28 UTC, danielfireman commented on src/output_test/expected_2018.json
> +                        "item": "Gratificação Natalina",
Qual o valor dessa e das outras?

2021-11-30 12:23 UTC, marcos-inja commented on src/output_test/expected_2018.json
> +                        "item": "Gratificação Natalina",
Não tem valor

2021-11-30 18:54 UTC, danielfireman-ifal approved these changes

2021-11-30 18:54 UTC, danielfireman-ifal commented on src/output_test/expected_2018.json
> +                        "item": "Gratificação Natalina",
Deve ser considerado zero, acho. Tudo bem.

2021-12-01 12:04 UTC, merged